# Generated by Django 4.1 on 2022-08-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Test", new_name="Movie",),
    ]
