# Generated by Django 4.1 on 2022-08-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_users_vote_movie_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
